
# RepMaster Database Configuration


# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/repmaster
spring.datasource.username=root
spring.datasource.password=RepMaster@2026!


# JPA / Hibernate Configuration
# Automatically update database tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true